SQLLDR.EXE student@student/student control='Pliki_ctl\miasto.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\adres.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\salon.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\stanowisko.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\wyplata.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\pracownik.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\klient.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\klient_salonu.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\typ_zabiegu.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\zabieg.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\wizyta.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\cena_zabiegu.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\dystrybutor.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\dostawa.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\produkt.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\produkt_w_dostawie.ctl'
SQLLDR.EXE student@student/student control='Pliki_ctl\cena_u_dystrybutora.ctl'
pause;
